version: 1.2
workflows:
   - name: "CRISPRi_pipeline"
     subclass: WDL
     primaryDescriptorPath: /CRISPRi_pipeline/CRISPRi_pipeline.wdl
     filters:
        branches:
          - main
        tags:
          - /.*/